version: '3'

services:
  redis-dev:
    container_name: redis-dev
    image: redis:3.2.10
    networks:
      devnet:
        aliases:
          - redis
    ports:
      - "6379:6379"
  es-dev:
    container_name: es-dev
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    # volumes:
    #   - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      devnet:
        aliases:
          - elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    volumes:
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml
      # - esdata:/usr/share/elasticsearch/data
  kibana-dev:
    container_name: kibana-dev
    image: docker.elastic.co/kibana/kibana:6.4.0
    networks:
        devnet:
          aliases:
            - kibana
    ports:
      - "5601:5601"


networks:
  devnet: